cadastros/urls.py
from django.urls import path
from .views import GroupCreateView, GroupDeleteView, GroupListView, GroupUpdateView, RegisterView, UpdateUserView, DeleteUserView, UserListView

urlpatterns = [
    path('cadastro/', RegisterView.as_view(), name='cadastro'),
    path('update-user/<int:pk>/', UpdateUserView.as_view(), name='update_user'),
    path('delete-user/<int:pk>/', DeleteUserView.as_view(), name='delete_user'),
    path('user-list/', UserListView.as_view(), name='user_list'),


    path('group-create/', GroupCreateView.as_view(), name='group_create'),
    path('group-update/<int:pk>/', GroupUpdateView.as_view(), name='group_update'),
    path('group-delete/<int:pk>/', GroupDeleteView.as_view(), name='group_delete'),
    path('group-list/', GroupListView.as_view(), name='group_list'),


]

eventos/urls.py
from django.urls import path
from eventos.views import AdicionarEventosView, PaginaEventosView


urlpatterns = [
    path('eventos/', PaginaEventosView.as_view(), name='eventos'),
    path('adicionar-eventos/', AdicionarEventosView.as_view(), name='adicionar-eventos'),

]

vrumVrum/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path("admin/", admin.site.urls),
    path('auth/', include('autenticacao.urls'))
]

vrumvrum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('autenticacao.urls')),
    path('admin/', admin.site.urls),
    path('', include ('cadastros.urls')),
    path('', include ('usuarios.urls')),
    path('', include ('semaforos.urls')),
    path('', include ('transito.urls')),
    path('', include ('acidentes.urls')),
    path('', include ('eventos.urls')),
]

cadastros/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
import random
import string
from django.core.mail import send_mail
from django.contrib.auth.hashers import make_password

def generate_random_string(length=8):
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for i in range(length))

def generate_random_password():
    return generate_random_string(10)

class CustomUserManager(BaseUserManager):
    def create_user(self, username, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        
        return self.create_user(username, email, password, **extra_fields)

class Cargo(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome

class Orgao(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome

class TipoAcesso(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome

class CustomUser(AbstractBaseUser, PermissionsMixin):
    nome_completo = models.CharField(max_length=100, help_text="Digite o nome completo")
    username = models.CharField(max_length=8, unique=True, default=generate_random_string)
    email = models.EmailField(unique=True, help_text="Digite o email")
    celular = models.CharField(max_length=15, default='')  # Valor padrão vazio para o celular
    cargo = models.ForeignKey(Cargo, on_delete=models.CASCADE, default=1, help_text="Selecione o cargo...")  # Valor padrão de 1 para o cargo
    orgao = models.ForeignKey(Orgao, on_delete=models.CASCADE, default=1, help_text="Selecione o orgão...")  # Valor padrão de 1 para o orgão
    setor = models.CharField(max_length=100, default='')  # Valor padrão vazio para o setor
    STATUS_CHOICES = [
        (True, 'Ativo'),
        (False, 'Inativo'),
    ] 
    status = models.BooleanField(default=True, choices=STATUS_CHOICES)  # Valor padrão de True para o status
    observacoes = models.TextField(blank=True, null=True, default='', help_text="Adicione quaisquer observações adicionais sobre o usuário")  # Valor padrão vazio para as observações
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def save(self, *args, **kwargs):
        if not self.pk:  # Apenas para novos usuários
            password = generate_random_password()
            self.set_password(password)
            send_mail(
                'Cadastro realizado com sucesso - Bem-vindo ao Vrum Vrum',
                f'Olá,\n\nParabéns! Seu cadastro no Vrum Vrum foi realizado com sucesso!\n\n'
                f'Aqui estão seus detalhes de login:\n\nLogin: {self.username}\n'
                f'Senha: {password}\n\nAgora você pode acessar sua conta no Vrum Vrum e começar a explorar todos os recursos disponíveis.\n\n'
                'Obrigado por se juntar a nós!\n\nAtenciosamente,\nEquipe Vrum Vrum',
                settings.EMAIL_HOST_USER,
                [self.email],
                fail_silently=False,
            )
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nome_completo

cadastros/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import Group, Permission
from django.core.exceptions import ValidationError
from .models import CustomUser, Cargo, Orgao, generate_random_password


class CustomUserCreationForm(UserCreationForm):
    cargo = forms.ModelChoiceField(queryset=Cargo.objects.all(), widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Selecione um cargo'}))
    orgao = forms.ModelChoiceField(queryset=Orgao.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(), widget=forms.CheckboxSelectMultiple, required=False)
    status = forms.ChoiceField(choices=CustomUser.STATUS_CHOICES, widget=forms.RadioSelect)

    class Meta:
        model = CustomUser
        fields = [
            'nome_completo',
            'username',
            'email',
            'celular',
            'cargo',
            'setor',
            'orgao',
            'groups',
            'status',
            'observacoes',
            'password1',
            'password2',
        ]
        widgets = {
            'username': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.instance.pk:  # Se é um novo usuário (cadastro)
            self.fields['password1'].required = False
            self.fields['password2'].required = False
            self.fields['password1'].widget.attrs['placeholder'] = 'Deixe em branco para gerar uma senha automaticamente'
            self.fields['password2'].widget.attrs['placeholder'] = 'Deixe em branco para gerar uma senha automaticamente'

    def clean_email(self):
            email = self.cleaned_data.get('email')
            if CustomUser.objects.filter(email=email).exists():
                raise forms.ValidationError(f"O email {email} já está em uso.")
            return email

    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data.get("password1")
        if password:
            user.password = make_password(password)
        else:
            user.set_password(generate_random_password())
        if commit:
            user.save()
            self.save_m2m()
        return user

class CustomUserChangeForm(UserChangeForm):
    cargo = forms.ModelChoiceField(queryset=Cargo.objects.all(), widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Selecione um cargo'}))
    orgao = forms.ModelChoiceField(queryset=Orgao.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(), widget=forms.CheckboxSelectMultiple, required=False)
    status = forms.ChoiceField(choices=CustomUser.STATUS_CHOICES, widget=forms.RadioSelect)
    password = forms.CharField(label="Senha", required=False, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Deixe em branco para manter a senha atual'}))

    class Meta:
        model = CustomUser
        fields = [ # Adicionar os campos
            'nome_completo',
            'username',
            'email',
            'celular',
            'cargo',
            'setor',
            'orgao',
            'groups',
            'status',
            'observacoes',
            'password', 
        ]
        widgets = {
            'username': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data.get("password")
        if password:
            user.set_password(password)
        if commit:
            user.save()
            self.save_m2m()
        return user


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name', 'permissions']

    permissions = forms.ModelMultipleChoiceField(
        queryset=Permission.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

cadastros/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import View
from django.contrib.auth import login
from .forms import CustomUserChangeForm, CustomUserCreationForm
from .forms import GroupForm
from django.contrib.auth.models import Group
from braces.views import GroupRequiredMixin
from .models import CustomUser, generate_random_password, generate_random_string


class RegisterView(GroupRequiredMixin, LoginRequiredMixin, View):
    login_url = reverse_lazy('login')
    group_required = u"Admnistrador"
    template_name = 'cadastros/index.html'

    def get(self, request, *args, **kwargs):
        form = CustomUserCreationForm()
        breadcrumb_items = [
            {'name': 'Administração', 'link': reverse('administracao')},
            {'name': 'Lista de Funcionários', 'link': reverse('user_list')},
            {'name': 'Cadastrar Funcionário', 'link': None},
        ]
        return render(request, self.template_name, {'form': form, 'breadcrumb_items': breadcrumb_items})


    def post(self, request, *args, **kwargs):
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = generate_random_string()
            if not user.password:
                user.set_password(generate_random_password())
            user.save()
            login(request, user)
            return redirect('menu-principal')
        return render(request, self.template_name, {'form': form})
    


########### ATUALIZAR OS DADOS DE UM USUARIO ###############

class UpdateUserView(GroupRequiredMixin, LoginRequiredMixin, View):
    login_url = reverse_lazy('login')
    group_required = u"Admnistrador"
    template_name = 'lista/editar-usuario.html'

    def get(self, request, *args, **kwargs):
        user = get_object_or_404(CustomUser, pk=self.kwargs['pk'])
        form = CustomUserChangeForm(instance=user)
        
        breadcrumb_items = [
            {'name': 'Administração', 'link': reverse('administracao')},
            {'name': 'Lista de Funcionários', 'link': reverse('user_list')},
            {'name': 'Editar Dados de Cadastro', 'link': None},
        ]
        
        return render(request, self.template_name, {'form': form, 'breadcrumb_items': breadcrumb_items})

    def post(self, request, *args, **kwargs):
        user = get_object_or_404(CustomUser, pk=self.kwargs['pk'])
        form = CustomUserChangeForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('user_list')
        return render(request, self.template_name, {'form': form})
    

    
############ EXCLUIR UM USUARIO ##############

class DeleteUserView(GroupRequiredMixin, LoginRequiredMixin, View):
    login_url = reverse_lazy('login')
    group_required = u"Admnistrador"
    template_name = 'lista/excluir-usuario.html'

    def get(self, request, *args, **kwargs):
        user = get_object_or_404(CustomUser, pk=self.kwargs['pk'])
        return render(request, self.template_name, {'user': user})

    def post(self, request, *args, **kwargs):
        user = get_object_or_404(CustomUser, pk=self.kwargs['pk'])
        user.delete()
        return redirect('user_list')
    

############# LISTAR OS USUARIOS ##############

class UserListView(LoginRequiredMixin, View):
    login_url = reverse_lazy('login')
    template_name = 'lista/usuarios.html'

    def get(self, request, *args, **kwargs):
        users = CustomUser.objects.all()
        breadcrumb_items = [
            {'name': 'Menu', 'link': reverse('menu-principal')},
            {'name': 'Administração', 'link': reverse('administracao')},
            {'name': 'Lista de Funcionários', 'link': None},
        ]
        return render(request, self.template_name, {'users': users, 'breadcrumb_items': breadcrumb_items})

############## CRIAR GRUPO DE USUÁRIOS ##############

class GroupCreateView(GroupRequiredMixin, LoginRequiredMixin, View):
    login_url = reverse_lazy('login')
    group_required = u"Admnistrador"
    template_name = 'grupos/criar_grupos.html'

    def get(self, request, *args, **kwargs):
        form = GroupForm()
        
        breadcrumb_items = [
            {'name': 'Administração', 'link': reverse('administracao')},
            {'name': 'Perfis de Acesso', 'link': reverse('group_list')},
            {'name': 'Cadastrar Grupo de Usuário', 'link': None},
        ]
        
        return render(request, self.template_name, {'form': form, 'breadcrumb_items': breadcrumb_items})

    def post(self, request, *args, **kwargs):
        form = GroupForm(request.POST)
        if form.is_valid():
            group = form.save()
            return redirect('group_list')
        
        breadcrumb_items = [
            {'name': 'Administração', 'link': reverse('administracao')},
            {'name': 'Perfis de Acesso', 'link': reverse('group_list')},
            {'name': 'Cadastrar Grupo de Usuário', 'link': None},
        ]
        
        return render(request, self.template_name, {'form': form, 'breadcrumb_items': breadcrumb_items})


    
############# ATUALIZAR GRUPO DE USUÁRIOS ##############

class GroupUpdateView(GroupRequiredMixin, LoginRequiredMixin, View):
    login_url = reverse_lazy('login')
    group_required = u"Admnistrador"
    template_name = 'grupos/editar_grupos.html'
    

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, pk=self.kwargs['pk'])
        form = GroupForm(instance=group)
        
        breadcrumb_items = [
            {'name': 'Administração', 'link': reverse('administracao')},
            {'name': 'Perfis de Acesso', 'link': reverse('group_list')},
            {'name': 'Editar Permissões de Usuário', 'link': None},
        ]
        
        return render(request, self.template_name, {'form': form, 'breadcrumb_items': breadcrumb_items})


    def post(self, request, *args, **kwargs):
        group = get_object_or_404(Group, pk=self.kwargs['pk'])
        form = GroupForm(request.POST, instance=group)
        if form.is_valid():
            group = form.save()
            return redirect('group_list')
        
        breadcrumb_items = [
            {'name': 'Administração', 'link': reverse('administracao')},
            {'name': 'Perfis de Acesso', 'link': reverse('group_list')},
            {'name': 'Editar Permissões de Usuário', 'link': None},
        ]
        
        return render(request, self.template_name, {'form': form, 'breadcrumb_items': breadcrumb_items})
    


############# EXCLUIR GRUPO DE USUÁRIOS ##############
    
class GroupDeleteView(GroupRequiredMixin, LoginRequiredMixin, View):
    login_url = reverse_lazy('login')
    group_required = u"Admnistrador"
    template_name = 'grupos/excluir_grupos.html'

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, pk=self.kwargs['pk'])
        return render(request, self.template_name, {'group': group})

    def post(self, request, *args, **kwargs):
        group = get_object_or_404(Group, pk=self.kwargs['pk'])
        group.delete()
        return redirect('group_list')
    

############# LISTAR GRUPO DE USUÁRIOS ##############

class GroupListView(LoginRequiredMixin, View):
    login_url = reverse_lazy('login')
    template_name = 'grupos/listar_grupos.html'


    def get(self, request, *args, **kwargs):
        groups = Group.objects.all()
        breadcrumb_items = [
            {'name': 'Menu', 'link': reverse('menu-principal')},
            {'name': 'Administração', 'link': reverse('administracao')},
            {'name': 'Lista de Perfis de Acesso', 'link': None},
        ]
        return render(request, self.template_name, {'groups': groups, 'breadcrumb_items': breadcrumb_items})

cadastros/templates/grupos/criar_grupos.html
{% extends "base.html" %}
{% load static %}


{% block title %}
Vrum Vrum | Cadastrar Perfil de Acesso
{% endblock %}

{%block 'head'%}
{% block additional_css %}
<link rel="stylesheet" href="{% static '/css/grupos.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
{% endblock %}
{%endblock%}

{% block content %}
<main role="main" class="col-md-9 col-lg-10 px-md-4 mt-3 p-3">
    {% block breadcrumbs %}
      {% include 'breadcrumbs.html' with breadcrumb_items=breadcrumb_items %}
    {% endblock %}
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Cadastrar Perfil de Acesso</h1>
</div>
<div class="form-container container-fluid">
  <form class="form" method="post">
    {% csrf_token %}
    <div class="form-group col-md-6">
      <label>Nome</label>
      {{ form.name }}
    </div>
    <br>
    <label for="id_permissions" class="permissions">Permissões</label>
    <div class="permissions-container">
      <div class="permissions-scroll">
        {{ form.permissions }}
      </div>
    </div>
    <br>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end mb-5 mx-auto">
      <button type="submit" class="btn btn-success">
        {% if form.instance.pk %}Atualizar{% else %}Adicionar{% endif %}
      </button>
    </div>
  </form>
</div>
</main>
{% endblock %}

cadastros/templates/grupos/editar_grupos.html
{% extends "base.html" %}
{% load static %}


{% block title %}
Vrum Vrum | Editar Permissões
{% endblock %}

{%block 'head'%}
{% block additional_css %}
<link rel="stylesheet" href="{% static '/css/grupos.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
{% endblock %}
{%endblock%}

{% block content %}
<div class="col-md-9 col-lg-10 px-md-4 mt-3 p-3">
  {% block breadcrumbs %}
       {% include 'breadcrumbs.html' with breadcrumb_items=breadcrumb_items %}
  {% endblock %}
</div>
<main role="main" class="col-md-9 col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Editar Permissões</h1>
</div>
<div class="form-container container-fluid">
  <form class="form" method="post">
    {% csrf_token %}
    <div class="form-group col-md-6">
      <label>Nome</label>
      {{ form.name }}
    </div>
    <br>
    <label for="id_permissions" class="permissions">Permissões</label>
    <div class="permissions-container">
      <div class="permissions-scroll">
        {{ form.permissions }}
      </div>
    </div>
    <br>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end mb-5 mx-auto">
      <button type="submit" class="btn btn-warning">
        {% if form.instance.pk %}Atualizar{% else %}Adicionar{% endif %}
      </button>
    </div>
  </form>
</div>
</main>
{% endblock %}

cadastros/templates/grupos/excluir_grupos.html
{% extends "base.html" %}
{% load static %}


{% block title %}
Vrum Vrum | Excluir Grupo de Acesso
{% endblock %}

{%block 'head'%}
{% block additional_css %}
<link rel="stylesheet" href="{% static '/css/cadastro.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
{% endblock %}
{%endblock%}

{% block content %}


<main role="main" class="col-md-9 col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Confirmação de Exclusão</h1>
    </div>
    <form method="POST" action="" class="row g-3">
        {% csrf_token %}

        <p>
            Você tem certeza que deseja excluir o grupo "{{ group.name }}"?
        </p>
  
        <button type="submit" class="col-md-4 btn btn-danger btn-block mx-1">Confirmar Exclusão</button>
        <a href="{% url 'group_list' %}" class="col-md-4 btn btn-secondary btn-block mx-1">Cancelar</a>
  </form>
</main>



{% endblock %}

cadastros/templates/grupos/listar_grupos.html
{% extends "base.html" %}
{% load static %}

<!-- {% load crispy_forms_tags %} -->

{% block title %}
Vrum Vrum | Perfis de Acesso
{% endblock %}

{%block 'head'%}
{% block additional_css %}
<link rel="stylesheet" href="{% static '/css/lista.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
{% endblock %}
{%endblock%}

{% block content %}

<div class="col-md-9 col-lg-10 px-md-4 mt-3 p-3">
    {% block breadcrumbs %}
         {% include 'breadcrumbs.html' with breadcrumb_items=breadcrumb_items %}
    {% endblock %}
  </div>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 mx-4 border-bottom">
    <h1 class="h2">Perfis de Acesso</h1>
</div>

 <!-- Tabela de perfis -->
<main class="table table-responsive mt-3 mx-4">
    <section class="table__header">
        <div class="input-group">
            <input type="search" placeholder="Pesquisar...">
        </div>
        <a href="{% url 'group_create' %}" class="btn btn-primary btn-sm">Adicionar Perfil</a>
    </section>
    <section class="table__body">
        <table>
            <thead>
                <tr>
                    <th>Id<span class="icon-arrow">&UpArrow;</span></th>
                    <th>Nome<span class="icon-arrow">&UpArrow;</span></th>
                    <th>Permissões<span class="icon-arrow">&UpArrow;</span></th>
                    <th>Opções</th>
                </tr>
            </thead>
            <tbody>
                {% for group in groups %}
                <tr>
                    <td>{{ group.id }}</td>
                    <td>{{ group.name }}</td>
                    <td>{{ perm.name }}</td>
                    <td>
                        <a href="{%url 'group_update' group.pk %}" class="btn btn-warning btn-sm" title="Editar">
                            <i class="bi bi-pencil-square"></i>
                        </a>
                        <a href="{%url 'group_delete' group.pk %}" class="btn btn-danger btn-sm" title="Excluir">
                            <i class="bi bi-trash"></i>
                        </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">Nenhum campo registrado.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
</main>

<script src="{% static 'js/script.js' %}"></script>

{% endblock %}